language: objective-c
osx_image: xcode9
script:
    - xcodebuild build test -sdk macosx -project Topaz.xcodeproj -scheme Topaz-Package CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES VALID_ARCHS=x86_64
after_success:
    - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
